#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-new"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "3217fbb9c60b4147b6a51abc382214b8" }
]

[assets]
directory = "./public"
